version: "3.8"

services:
  csgo-server-1:
    image: cm2network/csgo:latest
    container_name: csgo-server-1
    restart: unless-stopped
    ports:
      - "28000:28000" # Porta principal do servidor
      - "28000:28000/udp" # Porta UDP
      - "28020:27020/udp" # Porta SourceTV
    volumes:
      - /home/ubuntu/csgo:/home/steam/csgo-dedicated # Mapeamento direto para o diretório do servidor
    networks:
      - csgo-network

networks:
  csgo-network:
    driver: bridge
