services:
  cs2-server:
    image: joedwards32/cs2:latest
    restart: unless-stopped
    volumes:
      - /home/csgo/cs2:/home/steam/cs2-dedicated/
    networks:
      - csgo-network

networks:
  csgo-network:
    driver: bridge
