services:
  cs2-server:
    image: joedwards32/cs2:latest
    restart: unless-stopped
    environment:
      - SRCDS_TOKEN=${SRCDS_TOKEN:-}
      - CS2_PWD=${CS2_PWD:-}
      - CS2_RCONPW=admin123
      - CS2_PW=six321123
      - CS2_PORT=27015
      - CS2_STARTMAP=de_mirage
      - CS2_HOSTNAME="Qota Community Cs2 Server 1"
      - CS2_GAME_ALIAS=competitive
      - CS2_MAXPLAYERS=10
      - CS2_LAN=0
      - SRCDS_RCONPW=${SRCDS_RCONPW:-changeme}
      - SRCDS_PW=${SRCDS_PW:-}
      - SRCDS_PORT=${SRCDS_PORT:-27015}
      - SRCDS_TV_PORT=${SRCDS_TV_PORT:-27020}
      - SRCDS_MAXPLAYERS=${SRCDS_MAXPLAYERS:-16}
      - SRCDS_MAP=${SRCDS_MAP:-de_dust2}
      - SRCDS_GAMEMODE=${SRCDS_GAMEMODE:-casual}
      - SRCDS_REGION=${SRCDS_REGION:-0}
      - SRCDS_FPSMAX=${SRCDS_FPSMAX:-300}
      - SRCDS_FRIENDLYFIRE=${SRCDS_FRIENDLYFIRE:-0}
      - SRCDS_AUTOTEAMBALANCE=${SRCDS_AUTOTEAMBALANCE:-1}
      - SRCDS_LAN=${SRCDS_LAN:-0}
      - SRCDS_NOSPAWNENTITIES=${SRCDS_NOSPAWNENTITIES:-0}
      - SRCDS_HOSTNAME=${SRCDS_HOSTNAME:-CS2 Dedicated Server}
      - SRCDS_WORKSHOP_COLLECTION=${SRCDS_WORKSHOP_COLLECTION:-}
      - SRCDS_STARTMAP=${SRCDS_STARTMAP:-de_dust2}
      - SRCDS_MAPGROUP=${SRCDS_MAPGROUP:-mg_active}
      - SRCDS_ADDITIONAL_ARGS=${SRCDS_ADDITIONAL_ARGS:-}
      - SRCDS_MOD=${SRCDS_MOD:-}
    ports:
      - 28000:27015/udp
      - 28000:27015/tcp
      - 28020:27020/udp
      - 28020:27020/tcp
      - 28022:22/tcp
    stdin_open: true
    tty: true
    volumes:
      - /home/ubuntu/cs2:/home/steam/cs2-dedicated/
    networks:
      - csgo-network

networks:
  csgo-network:
    driver: bridge
